name: Build-real-state-app
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          version: 14
      - run: yarn install
      - run: yarn build
      - run : echo "evrything is ok !!"
